[Unit]
Requires=inference.slice
After=inference.slice

[Service]
Slice=inference.slice
OOMPolicy=kill
OOMScoreAdjust=900
Nice=10
IOSchedulingClass=idle
CPUWeight=10
IOWeight=10
AllowedCPUs=0-11,16-27
MemoryHigh=96G
MemoryMax=100G
MemorySwapMax=2G
TasksMax=2048
